import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import Image from "next/image";
import { cookies } from "next/headers";
import { jwtDecode } from "jwt-decode";
import { ThemeProvider } from "@/components/theme-provider"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  const cookieStore = await cookies();
  const SSToken: any = cookieStore.get('SSToken');
  function userInfo() {
    if (SSToken) {
      try {
        const decoded: any = jwtDecode(SSToken.value);
        return decoded?.data || {};
      } catch (error) {
        console.error("JWT decoding error:", error);
        return {};
      }
    } else {
      return {}
    }
  }
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="fixed bottom-4 right-4 bg-default-color p-3 rounded-full cursor-pointer">
            <Image src="/images/chatbot.webp" alt="" width={30} height={30} />
          </div>
          <Header></Header>
          {children}
          <Footer></Footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
